defmodule MoneyMorphWeb.Presenters.CurrencyPresenter do
  def currency_name("AUD"), do: "Australian Dollar"
  def currency_name("BGN"), do: "Bulgarian Lev"
  def currency_name("BRL"), do: "Brazilian Real"
  def currency_name("CAD"), do: "Canadian Dollar"
  def currency_name("CHF"), do: "Swiss Franc"
  def currency_name("CNY"), do: "Chinese Yuan"
  def currency_name("CZK"), do: "Czech Koruna"
  def currency_name("DKK"), do: "Danish Krone"
  def currency_name("EUR"), do: "Euro"
  def currency_name("GBP"), do: "British Pound"
  def currency_name("HKD"), do: "Hong Kong Dollar"
  def currency_name("HUF"), do: "Hungarian Forint"
  def currency_name("IDR"), do: "Indonesian Rupiah"
  def currency_name("ILS"), do: "Israeli Shekel"
  def currency_name("INR"), do: "Indian Rupee"
  def currency_name("ISK"), do: "Icelandic Krona"
  def currency_name("JPY"), do: "Japanese Yen"
  def currency_name("KRW"), do: "South Korean Won"
  def currency_name("MXN"), do: "Mexican Peso"
  def currency_name("MYR"), do: "Malaysian Ringgit"
  def currency_name("NOK"), do: "Norwegian Krone"
  def currency_name("NZD"), do: "New Zealand Dollar"
  def currency_name("PHP"), do: "Philippine Peso"
  def currency_name("PLN"), do: "Polish Zloty"
  def currency_name("RON"), do: "Romanian Leu"
  def currency_name("SEK"), do: "Swedish Krona"
  def currency_name("SGD"), do: "Singapore Dollar"
  def currency_name("THB"), do: "Thai Baht"
  def currency_name("TRY"), do: "Turkish Lira"
  def currency_name("USD"), do: "United States Dollar"
  def currency_name("ZAR"), do: "South African Rand"
end
